os:
- linux
- windows

language: go
go:
- 1.16.x

git:
  depth: false

env:
  - GO111MODULE=off

install:
  - go get github.com/mattn/goveralls
  - go get -u honnef.co/go/tools/cmd/staticcheck
  - go get github.com/wadey/gocovmerge

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then EXCLUDE_VENDOR=$(go list ./... | grep -v "/vendor/") && $(exit $(go fmt $(echo $EXCLUDE_VENDOR) | wc -l)) && go vet $(echo $EXCLUDE_VENDOR); fi
  - staticcheck ./...

script:
  - mkdir cov
  - go test -v -failfast -covermode=atomic -coverprofile=./cov/cmd.out ./cmd
  - go test -v -failfast -covermode=atomic -coverprofile=./cov/store.out ./cmd/store
  - gocovmerge ./cov/*.out > coverage.out

deploy:
- provider: script
  cleanup: false
  script: $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service travis-ci
  on:
    condition: $TRAVIS_OS_NAME = linux

- provider: script
  cleanup: false
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux AND $TRAVIS_GO_VERSION =~ 1.16
